### ISSUE TITLE
Uncaught TypeError: Cannot read property 'trim' of undefined

### ISSUE THREAD

**Issue by johnhabibi** [gregorym/atom-inline-blame#8]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.37.0 x64
**Electron**: 2.0.18
**OS**: Mac OS X 10.14.5
**Thrown From**: [atom-inline-blame](https://github.com/gregorym/atom-inline-blame) package 0.0.6

### Stack Trace

Uncaught TypeError: Cannot read property 'trim' of undefined

```
At /Users/jhabibi/.atom/packages/atom-inline-blame/lib/InlineBlameView.js:56

TypeError: Cannot read property 'trim' of undefined
    at InlineBlameView.updateLine (/packages/atom-inline-blame/lib/InlineBlameView.js:56:58)
    at /packages/atom-inline-blame/lib/InlineBlameView.js:42:9
```

### Commands

```
```

### Non-Core Packages

```
aligner 1.2.4 
aligner-css 1.2.1 
aligner-javascript 1.3.0 
aligner-ruby 1.7.0 
aligner-scss 1.3.1 
atom-beautify 0.33.4 
atom-inline-blame 0.0.6 
atom-material-syntax 1.0.8 
atom-material-syntax-dark 1.0.0 
atom-material-ui 2.1.3 
busy-signal 2.0.1 
city-lights-syntax 1.1.8 
city-lights-ui 1.5.3 
elm-format 3.2.0 
file-icons 2.1.32 
fonts 3.4.0 
intentions 1.1.5 
language-dots 0.0.4 
language-elm 1.5.0 
linter 2.3.0 
linter-ui-default 1.7.1 
pigments 0.40.2 
prettier-atom 0.56.5 
pure-ui 1.0.4 
rails-snippets 2.21.0 
railscast-theme 0.4.0 
react 0.18.0 
rspec 0.4.0 
script 3.18.1 
seti-syntax 1.2.0 
seti-ui 1.11.0 
teletype 0.13.4 
unity-ui 2.1.11 
```

**Comment by itz-azhar** [comment]
Why is it closed? Still happing
